export type UiLanguage = 'zh-HK' | 'zh-TW' | 'en' | 'ja';

const en = {
  hideSettings: 'Hide settings',
  matchSettings: 'Match settings',
  playerSettings: 'Player settings',
  saveHide: 'Save & hide',
  startBattle: 'Start battle',
  stopReset: 'Stop / reset',
  startCamera: 'Start camera',
  stopCamera: 'Stop camera',
  cameraStopped: 'Camera stopped',
  cameraActive: 'Camera + MediaPipe active',
  cameraFailed: 'Camera failed',
  snapshotFailed: 'Snapshot upload failed',
  robotFailed: 'Robot technique failed',
  robotCooldownRemaining: (seconds: number) => `Robot cooldown ${seconds}s`,
  popupRequired: 'Open the media popup to play the technique',
  popupReady: 'popup ready',
  success: 'SUCCESS!',
  roundStopped: 'ROUND STOPPED',
  roundComplete: 'ROUND COMPLETE',
  perfect: 'PERFECT!',
  solo: 'SOLO',
  loading: 'loading',
  connecting: 'connecting',
  connected: 'connected',
  disconnected: 'disconnected',
  target: 'TARGET',
  score: 'Score',
  detected: 'Detected',
  waitingBattle: 'Waiting for battle',
  getReady: 'GET READY',
  scoreLocked: 'SCORE LOCKED',
  techniqueActivated: 'TECHNIQUE ACTIVATED',
  battleComplete: 'BATTLE COMPLETE',
  finished: 'FINISHED',
  prepareNext: 'PREPARE NEXT TECHNIQUE',
  prepareNextShort: 'PREPARE NEXT',
  startSoloRound: 'Start a solo round',
  localSoloRound: 'Local solo round',
  room: 'Room',
  role: 'Role',
  playerLabel: (number: number) => `PLAYER ${number}`,
  mode: 'Mode',
  onlineBattle: 'Online battle',
  soloGame: 'Solo mini-game',
  startRound: 'Start round',
  quit: 'Quit',
  camera: 'Camera',
  defaultCamera: 'Default camera',
  language: 'Language',
  video: 'Video',
  integratedSound: 'Integrated with sound',
  integratedSilent: 'Integrated silent',
  popupTab: 'Popup tab',
  noVideo: 'No video',
  autoOpenPopup: 'Auto-open popup',
  openMediaPopup: 'Open media popup',
  roundSeconds: 'Round seconds',
  techniques: 'Techniques',
  robot: 'Robot',
  allRobots: 'All robots',
  robotCooldown: 'Robot cooldown',
  disableRobotApi: 'Disable robot API',
  openBattleViewer: 'Open battle viewer',
  finalScore: 'Final score',
  playAgain: 'Play again',
  close: 'Close',
  countdown: 'Countdown',
  seconds: 'Seconds',
  scoreGrace: 'Score grace',
  sameGesture: 'Same gesture for both players',
  layout: 'Layout',
  sideBySide: 'Side-by-side',
  verticalStack: 'Vertical stack',
  dynamicView: 'Dynamic cinematic view',
  aiCommentator: 'AI commentator',
  enabled: 'Enabled',
  engine: 'Engine',
  tts: 'TTS',
  voice: 'Voice',
  auto: 'Auto',
  volume: 'Volume',
  captureSnapshots: 'Capture start/end snapshots',
  imagePolicy: 'Image policy',
  always: 'Always',
  startEnd: 'Start/end',
  never: 'Never',
  trashTalk: 'Trash talk',
  avatarSize: 'Avatar size',
  resetDefaults: 'Reset defaults',
  commentatorDisabled: 'Commentator disabled.',
  commentaryReady: 'Commentary is ready.',
  preparingCommentary: 'NOW LOADING OPENING COMMENTARY...',
  equalPower: 'EQUAL POWER',
  victory: 'VICTORY',
  perfectVictory: 'PERFECT VICTORY',
  drawMatch: 'DRAW MATCH',
  playerWins: (number: number) => `PLAYER ${number} WINS`,
  backLobby: 'Back to lobby',
  skipResult: 'Skip result video',
  skipCinematic: 'Skip cinematic',
  scrollTitle: '📜 Scroll of Honor (領域展影)',
  resultTitle: 'DOMAIN CLASH RESULT',
  noSession: 'No session supplied',
  loadingCaptures: 'Loading player captures…',
  capturesRequireApi: 'Player captures require the server API.',
  noMatchSession: 'No match session was supplied.',
  capturesUnavailable: 'Player captures are not available yet.',
  loadCapturesFailed: 'Unable to load player captures.',
  shareCopied: 'Share link copied to clipboard.',
  copyResultLink: 'Copy this result link:',
  waitingForPlayer: (number: number) => `Waiting for player ${number}`,
  playerCaptureAlt: (number: number) => `Player ${number} match capture`,
  downloadImages: 'Download images',
  shareResult: 'Share result',
  waitingStream: (number: number) => `Waiting for player ${number} stream`
};

const localized: Record<UiLanguage, Partial<typeof en>> = {
  en: {},
  'zh-HK': {
    hideSettings: '隱藏設定', matchSettings: '戰局設定', playerSettings: '玩家設定',
    saveHide: '儲存並隱藏', startBattle: '開始對決', stopReset: '停止 / 重設戰局',
    startCamera: '啟動鏡頭', stopCamera: '停止鏡頭', target: '目標術式', score: '分數',
    cameraStopped: '鏡頭已停止', cameraActive: '鏡頭及 MediaPipe 已啟動',
    cameraFailed: '鏡頭啟動失敗', snapshotFailed: '鏡頭截圖上載失敗',
    robotFailed: '機械人術式執行失敗', robotCooldownRemaining: (seconds) => `機械人冷卻尚餘 ${seconds} 秒`,
    popupRequired: '請開啟影片分頁以播放術式', popupReady: '影片分頁已準備',
    success: '成功！', roundStopped: '回合已停止', roundComplete: '回合完成',
    perfect: '完美完成！', solo: '單人', loading: '載入中', connecting: '連線中',
    connected: '已連線', disconnected: '連線中斷',
    detected: '偵測到', waitingBattle: '等待對決開始', getReady: '準備展開',
    scoreLocked: '分數確認中', techniqueActivated: '術式發動', battleComplete: '對決完成',
    finished: '已完成', prepareNext: '準備下一個術式', prepareNextShort: '準備下一式',
    startSoloRound: '開始單人回合', localSoloRound: '本機單人回合', room: '房間',
    role: '角色', playerLabel: (number) => `玩家 ${number}`, mode: '模式', onlineBattle: '網上對決', soloGame: '單人小遊戲',
    startRound: '開始回合', quit: '退出', camera: '鏡頭', defaultCamera: '預設鏡頭',
    language: '語言', video: '影片播放', integratedSound: '整合播放（有聲）',
    integratedSilent: '整合播放（靜音）', popupTab: '彈出分頁', noVideo: '不播放影片',
    autoOpenPopup: '自動開啟影片分頁', openMediaPopup: '開啟影片分頁',
    roundSeconds: '每回合秒數', techniques: '術式數量', robot: '機械人',
    allRobots: '所有機械人', robotCooldown: '機械人冷卻時間',
    disableRobotApi: '停用機械人 API', openBattleViewer: '開啟對決畫面',
    finalScore: '最終分數', playAgain: '再玩一次', close: '關閉', countdown: '倒數時間',
    seconds: '術式限時', scoreGrace: '評分寬限', sameGesture: '雙方使用相同術式',
    layout: '畫面排版', sideBySide: '左右並排', verticalStack: '上下雙層',
    dynamicView: '動態術式影片畫面', aiCommentator: 'AI 旁白解說', enabled: '啟用',
    engine: '解說引擎', tts: '語音合成', voice: '配音員', auto: '自動選擇',
    volume: '音量', captureSnapshots: '擷取開始及結束鏡頭',
    imagePolicy: '影像傳送設定', always: '每次傳送', startEnd: '只限開始及結束',
    never: '永不傳送', trashTalk: '垃圾話模式',
    avatarSize: '旁白頭像大小', resetDefaults: '重設預設值',
    commentatorDisabled: 'AI 旁白已停用。', commentaryReady: '旁白已準備。',
    preparingCommentary: '正在載入開場旁白…', equalPower: '勢均力敵', victory: '勝利',
    perfectVictory: '完美勝利', drawMatch: '平手', playerWins: (number) => `${number} 號術師勝出`,
    backLobby: '返回大堂', skipResult: '跳過結局動畫', skipCinematic: '跳過術式動畫',
    scrollTitle: '📜 領域展影 - 榮譽卷軸', resultTitle: '領域對決結果',
    noSession: '未提供對戰場次', loadingCaptures: '正在載入玩家截圖…',
    capturesRequireApi: '玩家截圖需要伺服器 API。',
    noMatchSession: '未提供對戰場次。', capturesUnavailable: '玩家截圖尚未提供。',
    loadCapturesFailed: '無法載入玩家截圖。',
    shareCopied: '分享連結已複製。', copyResultLink: '複製結果連結：',
    waitingForPlayer: (number) => `等待玩家 ${number}`, playerCaptureAlt: (number) => `玩家 ${number} 對戰截圖`,
    downloadImages: '下載圖片',
    shareResult: '分享結果', waitingStream: (number) => `等待玩家 ${number} 畫面`
  },
  'zh-TW': {
    hideSettings: '隱藏設定', matchSettings: '對戰設定', playerSettings: '玩家設定',
    saveHide: '儲存並隱藏', startBattle: '開始對戰', stopReset: '停止 / 重設對戰',
    startCamera: '啟動相機', stopCamera: '停止相機', target: '目標術式', score: '分數',
    cameraStopped: '相機已停止', cameraActive: '相機及 MediaPipe 已啟動',
    cameraFailed: '相機啟動失敗', snapshotFailed: '相機截圖上傳失敗',
    robotFailed: '機器人術式執行失敗', robotCooldownRemaining: (seconds) => `機器人冷卻尚餘 ${seconds} 秒`,
    popupRequired: '請開啟影片分頁以播放術式', popupReady: '影片分頁已準備',
    success: '成功！', roundStopped: '回合已停止', roundComplete: '回合完成',
    perfect: '完美完成！', solo: '單人', loading: '載入中', connecting: '連線中',
    connected: '已連線', disconnected: '連線中斷',
    detected: '偵測到', waitingBattle: '等待對戰開始', getReady: '準備展開',
    scoreLocked: '分數確認中', techniqueActivated: '術式發動', battleComplete: '對戰完成',
    finished: '已完成', prepareNext: '準備下一個術式', prepareNextShort: '準備下一式',
    startSoloRound: '開始單人回合', localSoloRound: '本機單人回合', room: '房間',
    role: '角色', playerLabel: (number) => `玩家 ${number}`, mode: '模式',
    onlineBattle: '線上對戰', soloGame: '單人小遊戲', startRound: '開始回合',
    quit: '退出', camera: '相機', defaultCamera: '預設相機', language: '語言',
    video: '影片播放', integratedSound: '整合播放（有聲）', integratedSilent: '整合播放（靜音）',
    popupTab: '彈出分頁', noVideo: '不播放影片', autoOpenPopup: '自動開啟影片分頁',
    openMediaPopup: '開啟影片分頁', roundSeconds: '每回合秒數', techniques: '術式數量',
    robot: '機器人', allRobots: '所有機器人', robotCooldown: '機器人冷卻時間',
    disableRobotApi: '停用機器人 API', openBattleViewer: '開啟對戰畫面',
    finalScore: '最終分數', playAgain: '再玩一次', close: '關閉', countdown: '倒數時間',
    seconds: '術式限時', scoreGrace: '評分寬限', sameGesture: '雙方使用相同術式',
    layout: '畫面配置', sideBySide: '左右並排', verticalStack: '上下排列',
    dynamicView: '動態術式影片畫面', aiCommentator: 'AI 旁白解說', enabled: '啟用',
    engine: '解說引擎', tts: '語音合成', voice: '配音員', auto: '自動選擇',
    volume: '音量', captureSnapshots: '擷取開始及結束畫面', imagePolicy: '影像傳送設定',
    always: '每次傳送', startEnd: '只限開始及結束', never: '永不傳送',
    trashTalk: '垃圾話模式', avatarSize: '旁白頭像大小',
    resetDefaults: '重設預設值', commentatorDisabled: 'AI 旁白已停用。',
    commentaryReady: '旁白已準備。', preparingCommentary: '正在載入開場旁白…',
    backLobby: '返回大廳', skipResult: '跳過結局動畫', skipCinematic: '跳過術式動畫',
    equalPower: '勢均力敵', victory: '勝利', perfectVictory: '完美勝利',
    drawMatch: '平手', playerWins: (number) => `玩家 ${number} 勝出`,
    scrollTitle: '📜 領域展影 - 榮譽卷軸', resultTitle: '領域對戰結果',
    noSession: '未提供對戰場次', loadingCaptures: '正在載入玩家截圖…',
    capturesRequireApi: '玩家截圖需要伺服器 API。',
    noMatchSession: '未提供對戰場次。', capturesUnavailable: '玩家截圖尚未提供。',
    loadCapturesFailed: '無法載入玩家截圖。',
    shareCopied: '分享連結已複製。', copyResultLink: '複製結果連結：',
    waitingForPlayer: (number) => `等待玩家 ${number}`, playerCaptureAlt: (number) => `玩家 ${number} 對戰截圖`,
    downloadImages: '下載圖片',
    shareResult: '分享結果', waitingStream: (number) => `等待玩家 ${number} 畫面`
  },
  ja: {
    hideSettings: '設定を隠す', matchSettings: '対戦設定', playerSettings: 'プレイヤー設定',
    saveHide: '保存して閉じる', startBattle: 'バトル開始', stopReset: '停止 / リセット',
    startCamera: 'カメラ開始', stopCamera: 'カメラ停止', target: '対象術式', score: 'スコア',
    cameraStopped: 'カメラ停止中', cameraActive: 'カメラと MediaPipe が作動中',
    cameraFailed: 'カメラの起動に失敗しました', snapshotFailed: 'スナップショットの送信に失敗しました',
    robotFailed: 'ロボット術式の実行に失敗しました', robotCooldownRemaining: (seconds) => `ロボット待機時間 ${seconds}秒`,
    popupRequired: '術式を再生するには動画タブを開いてください', popupReady: '動画タブ準備完了',
    success: '成功！', roundStopped: 'ラウンド停止', roundComplete: 'ラウンド完了',
    perfect: 'パーフェクト！', solo: 'ソロ', loading: '読み込み中', connecting: '接続中',
    connected: '接続済み', disconnected: '切断',
    detected: '検出', waitingBattle: 'バトル待機中', getReady: '構えろ',
    scoreLocked: '判定中', techniqueActivated: '術式発動', battleComplete: '対戦終了',
    finished: '完了', prepareNext: '次の術式を準備', prepareNextShort: '次の術式',
    startSoloRound: 'ソロラウンド開始', localSoloRound: 'ローカルソロ', room: 'ルーム',
    role: '役割', playerLabel: (number) => `プレイヤー ${number}`, mode: 'モード',
    onlineBattle: 'オンライン対戦', soloGame: 'ソロミニゲーム', startRound: 'ラウンド開始',
    quit: '終了', camera: 'カメラ', defaultCamera: '標準カメラ', language: '言語',
    video: '動画', integratedSound: '画面内再生（音声あり）', integratedSilent: '画面内再生（ミュート）',
    popupTab: '別タブ', noVideo: '動画なし', autoOpenPopup: '動画タブを自動で開く',
    openMediaPopup: '動画タブを開く', roundSeconds: 'ラウンド秒数', techniques: '術式数',
    robot: 'ロボット', allRobots: 'すべてのロボット', robotCooldown: 'ロボット待機時間',
    disableRobotApi: 'ロボット API を無効化', openBattleViewer: '対戦画面を開く',
    finalScore: '最終スコア', playAgain: 'もう一度', close: '閉じる', countdown: 'カウントダウン',
    seconds: '制限時間', scoreGrace: '判定猶予', sameGesture: '両プレイヤーに同じ術式',
    layout: 'レイアウト', sideBySide: '左右表示', verticalStack: '上下表示',
    dynamicView: '動的な術式動画表示', aiCommentator: 'AI 実況', enabled: '有効',
    engine: 'エンジン', tts: '音声合成', voice: '音声', auto: '自動',
    volume: '音量', captureSnapshots: '開始・終了時の画像を保存', imagePolicy: '画像ポリシー',
    always: '常時', startEnd: '開始・終了時', never: 'なし', trashTalk: '挑発モード',
    avatarSize: 'アバターサイズ',
    resetDefaults: '初期設定に戻す', commentatorDisabled: 'AI 実況は無効です。',
    commentaryReady: '実況準備完了。', preparingCommentary: 'オープニング実況を読み込み中…',
    backLobby: 'ロビーに戻る', skipResult: '結果動画をスキップ',
    skipCinematic: '術式動画をスキップ', equalPower: '互角', victory: '勝利',
    perfectVictory: '完全勝利', drawMatch: '引き分け',
    playerWins: (number) => `プレイヤー ${number} 勝利`,
    scrollTitle: '📜 領域展影・栄誉の巻物', resultTitle: '領域対戦結果',
    noSession: 'セッションが指定されていません', loadingCaptures: 'プレイヤー画像を読み込み中…',
    capturesRequireApi: 'プレイヤー画像にはサーバー API が必要です。',
    noMatchSession: '対戦セッションが指定されていません。',
    capturesUnavailable: 'プレイヤー画像はまだ利用できません。',
    loadCapturesFailed: 'プレイヤー画像を読み込めません。',
    shareCopied: '共有リンクをコピーしました。', copyResultLink: '結果リンクをコピー：',
    waitingForPlayer: (number) => `プレイヤー ${number} を待機中`,
    playerCaptureAlt: (number) => `プレイヤー ${number} の対戦画像`,
    downloadImages: '画像をダウンロード', shareResult: '結果を共有',
    waitingStream: (number) => `プレイヤー ${number} の映像を待機中`
  }
};

const translations: Record<UiLanguage, typeof en> = {
  en,
  'zh-HK': { ...en, ...localized['zh-HK'] },
  'zh-TW': { ...en, ...localized['zh-TW'] },
  ja: { ...en, ...localized.ja }
};

export const uiText = (language: UiLanguage) => translations[language];
